version: "3.8"
services:
  postgres:
    image: postgres:14.3-alpine
    container_name: postgres
    restart: always
    ports:
      - "27041:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB = onlineestore

  admin:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
