# Generated by Django 4.2 on 2023-05-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='amount',
        ),
    ]
