# Generated by Django 4.2 on 2023-05-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_discount_amount_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='prior_salary',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='line_item',
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
